name: Generate snake animation

# Gatilhos do workflow
on:
  schedule:
    # Roda todo dia à meia-noite
    - cron: "0 0 * * *"
  
  # Permite rodar manualmente pela aba "Actions" do GitHub
  workflow_dispatch:

# Definição dos trabalhos (jobs) a serem executados
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para o job escrever no repositório

    steps:
      # Passo 1: Faz o checkout do código para a action ter acesso ao repo
      - uses: actions/checkout@v3

      # Passo 2: Gera os arquivos da animação da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Passo 3: Faz o commit e push dos arquivos gerados para o branch 'output'
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}